-- ====================================================================
-- PREMIUM SUPABASE DATABASE SCHEMA FOR C-LAB PORTAL
-- 
-- Copy and execute this script inside the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/boqbligtmjlsrawpffjh/sql
-- ====================================================================

-- 1. Create automatic updated_at trigger helper function (Safe update)
CREATE OR REPLACE FUNCTION public.handle_update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Create labs table (IF NOT EXISTS preserves existing data)
CREATE TABLE IF NOT EXISTS public.labs (
    "labNum" integer PRIMARY KEY,
    tutorial text NOT NULL,
    title text NOT NULL,
    problems jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create theory table (IF NOT EXISTS preserves existing data)
CREATE TABLE IF NOT EXISTS public.theory (
    "labNum" integer PRIMARY KEY,
    concept text NOT NULL,
    summary text NOT NULL,
    "keyPoints" jsonb NOT NULL DEFAULT '[]'::jsonb,
    explanation text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create quizzes table (IF NOT EXISTS preserves existing data)
CREATE TABLE IF NOT EXISTS public.quizzes (
    "labNum" integer PRIMARY KEY,
    questions jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create links table (IF NOT EXISTS preserves existing data)
CREATE TABLE IF NOT EXISTS public.links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    url text NOT NULL,
    description text,
    category text DEFAULT 'General'::text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Attach auto-update triggers to keep track of modifications (Safe check)
DROP TRIGGER IF EXISTS trigger_update_labs_timestamp ON public.labs;
CREATE TRIGGER trigger_update_labs_timestamp
    BEFORE UPDATE ON public.labs
    FOR EACH ROW EXECUTE FUNCTION public.handle_update_timestamp();

DROP TRIGGER IF EXISTS trigger_update_theory_timestamp ON public.theory;
CREATE TRIGGER trigger_update_theory_timestamp
    BEFORE UPDATE ON public.theory
    FOR EACH ROW EXECUTE FUNCTION public.handle_update_timestamp();

DROP TRIGGER IF EXISTS trigger_update_quizzes_timestamp ON public.quizzes;
CREATE TRIGGER trigger_update_quizzes_timestamp
    BEFORE UPDATE ON public.quizzes
    FOR EACH ROW EXECUTE FUNCTION public.handle_update_timestamp();

DROP TRIGGER IF EXISTS trigger_update_links_timestamp ON public.links;
CREATE TRIGGER trigger_update_links_timestamp
    BEFORE UPDATE ON public.links
    FOR EACH ROW EXECUTE FUNCTION public.handle_update_timestamp();

-- 7. Enable Row Level Security (RLS) on all tables to lock them down
ALTER TABLE public.labs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.theory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.links ENABLE ROW LEVEL SECURITY;

-- 8. Create Read Policies: Allow anyone (even unauthenticated visitors) to select/read the data
DROP POLICY IF EXISTS "Allow public read access" ON public.labs;
CREATE POLICY "Allow public read access" ON public.labs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.theory;
CREATE POLICY "Allow public read access" ON public.theory FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.quizzes;
CREATE POLICY "Allow public read access" ON public.quizzes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.links;
CREATE POLICY "Allow public read access" ON public.links FOR SELECT USING (true);

-- 9. Create Write Policies: Allow only authenticated administrators to insert, update, or delete data
DROP POLICY IF EXISTS "Allow admin write access" ON public.labs;
CREATE POLICY "Allow admin write access" ON public.labs FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin write access" ON public.theory;
CREATE POLICY "Allow admin write access" ON public.theory FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin write access" ON public.quizzes;
CREATE POLICY "Allow admin write access" ON public.quizzes FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin write access" ON public.links;
CREATE POLICY "Allow admin write access" ON public.links FOR ALL TO authenticated USING (true) WITH CHECK (true);
